spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testgen?useSSL=false&serverTimezone=UTC
    username: testgen
    password: testgen
  jpa:
    database-platform: org.eclipse.persistence.platform.database.MySQLPlatform
    properties:
      eclipselink:
        target-database: org.eclipse.persistence.platform.database.MySQLPlatform
        weaving: false
        logging.level: INFO
      jakarta:
        persistence:
          schema-generation:
            database.action: none
  flyway:
    locations: classpath:db/migration
server:
  port: 8080

app:
  cors:
    allowed-origins: http://localhost:5173
